### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by TheSYNcoder** [TheSYNcoder/JuCC#12]
# Feature Request
## Summary
Add further documentation, specially in the main README.md file about the files in the project and what they do.

More details should be added instead of nothing yet.

**Comment by noob77777** [comment]
:+1:
Also add a logo

**Comment by noob77777** [comment]
logo: ![logo](https://user-images.githubusercontent.com/42897033/116920657-8acdf480-ac70-11eb-8d3f-46cf27fcb1a1.png)
