### ISSUE TITLE
Fix: grammar and lexer

### ISSUE THREAD

**Issue by noob77777** [TheSYNcoder/JuCC#13]
# Bug Report
Make grammar and lexer consistent with problem statement.

### Some features are still missing in main branch *grammar* and *lexer*.
Data Type : integer (int), floating point (float) and void
Declaration statements : identifiers are declared in declaration statements as basic data types and may also be assigned constant values (integer of floating)
Condition constructs: if, else, nested statements are supported. There may be if statement without else statement.
Assignments to the variables are performed using the input / output constructs:
        cin >> x - Read into variable x
        cout << x - Write variable x to output 
Only arithmetic operators {+, -, *, %} and assignment operator `=’ are     supported
Relational operators used in the if statement are < (less than), > (greater than), == (equal) and != (not equal)
Only function is main(), there is no other function. The main() function does not contain arguments and no return statements.

### Expected Behavior
Rule for following operators should be present in grammar:
- %

Support for additional tokens: 
 - \>=
 - <=
 - !=
 - \+
 - \-
 - \*
 - /
 - %

## Solution
Update grammar.g file and lexer.

**Comment by TheSYNcoder** [comment]
Yes.
The lexer needs to add support for arithmetic tokens, and relational operators.
Nice observation.


Can only one main function be taken care of by the grammar ?

**Comment by noob77777** [comment]
Current grammar doesn't constraint *main* function to be named *main*. It accepts any identifier.
Should this constrain be taken care by the grammar or some semantic analyzer after parse tree is generated? 
Similarly grammar allows \<expression\> << \<expression\> and does not constrain it to be *cout* or *cin* for cascading and expression support.

**Comment by TheSYNcoder** [comment]
I don't think it is the job of a semantic analyzer. Semantic analyzer checks for faulty datatypes and other statements which are parsed successfully. 
However a statement such as `int random_function()` should not be parsed in the first place.
grammar can be like

initial : ..
..
function : < datatype > < id > <paran_open> <paran_close>
id : main
