### ISSUE TITLE
Improvement in grammar.

### ISSUE THREAD

**Issue by TheSYNcoder** [TheSYNcoder/JuCC#21]
## Summary
No cout, cin terminals in current grammar, in `src/grammar/grammar.g`

## Solution
The grammar should be able to support cout, cin and should have its respective rules.

___

**Comment by noob77777** [comment]
grammar accepts expression << expression. And expression can be an identifier. Type checking is not the job of grammar. As far as grammar is concerned it will treat cin, cout as any other identifier. Type checking and if those symbols are defined is part of semantic analysis.

**Comment by TheSYNcoder** [comment]
The cin, cout should be defined as terminals of the grammar. ( cin , cout are reserved words and cannot be simply used as a regular identifier).
The rule part seems okay.

**Comment by noob77777** [comment]
Ok will look into it
