### ISSUE TITLE
Symbol Table bug for undeclared symbols.

### ISSUE THREAD

**Issue by noob77777** [TheSYNcoder/JuCC#42]
# Bug Report
## Summary
for declarations like int x, y; y is detected as a undeclared symbol.

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: Ubuntu (LTS) 20.04 or macOS 10.14+

**Compiler**: GCC 7.0+ or Clang 8.0+

**CMake Profile**: `all`

## Steps to Reproduce
in.cc
```
int main() {
    int x, y;
}

```

### Expected Behavior
y is declared.

### Actual Behavior
```
jucc: undelared symbol: y
```

**Comment by TheSYNcoder** [comment]
Okay this will be tough.
Because the current data-type is checked before every symbol.
