### ISSUE TITLE
Duplicate Symbols in Symbol Table

### ISSUE THREAD

**Issue by noob77777** [TheSYNcoder/JuCC#46]
# Bug Report

## Summary
Symbol Table bug

## Environment
To address the bug, especially if it environment specific, we need to know what kind of configuration you are running on. Please include the following:

**OS**: Ubuntu (LTS) 20.04 or macOS 10.14+ (please specify version).

**Compiler**: GCC 7.0+ or Clang 8.0+. 

**CMake Profile**: `all`

## Steps to Reproduce
```

int main() {
    int x, y;
    cin >> x >> y;
    if (x != 0) {
        if (y > 0) {
            cout << y;
        } else {
            cout << -y;
        }
    }
    float z = 1 + 2 + 3 + 1000/ 50 * 23.2 * (x * y * 10);
    // cout << x << y << z;
    float z0 = 1 + 2 + 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z1 = 1 + 2 - 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z2 = 1 + 2 / 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z3 = 1 + 2 * 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z4 = 1 + 2 % 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z5 = 1 + 2 > 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z6 = 1 + 2 == 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z7 = 1 + 2 != 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z8 = 1 + 2 >= 3 + 1000/ 50 * 23.2 * (x * y * 10);
    float z9 = 1 + 2 <= 3 + 1000/ 50 * 23.2 * (x * y * 10);
    cout << z0 << z1 << z2 << z3 << z4;
    cout << z5 << z6 << z7 << z8 << z9;
}

```

### Expected Behavior
ok

### Actual Behavior

jucc: duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y
duplicate symbol: x
duplicate symbol: y

**Comment by TheSYNcoder** [comment]
F okay

**Comment by bisakhmondal** [comment]
😎
bugs are getting smart!!
